"""final revision

Revision ID: 6f164ecda313
Revises: 9b7d07916aac
Create Date: 2023-07-15 11:26:51.285485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f164ecda313'
down_revision = '9b7d07916aac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exos', sa.Column('input_', sa.String(), nullable=True))
    op.add_column('exos', sa.Column('output', sa.String(), nullable=True))
    op.drop_column('exos', 'test_cases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exos', sa.Column('test_cases', sa.VARCHAR(), nullable=True))
    op.drop_column('exos', 'output')
    op.drop_column('exos', 'input_')
    # ### end Alembic commands ###
