"""last revision

Revision ID: 9b7d07916aac
Revises: 
Create Date: 2023-07-15 11:22:40.431742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7d07916aac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_testcases_id', table_name='testcases')
    op.drop_table('testcases')
    op.add_column('exos', sa.Column('test_cases', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exos', 'test_cases')
    op.create_table('testcases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('input_', sa.VARCHAR(), nullable=True),
    sa.Column('output', sa.VARCHAR(), nullable=True),
    sa.Column('exo_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_testcases_id', 'testcases', ['id'], unique=False)
    # ### end Alembic commands ###
